name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'android-14'

jobs:
  build_aqua:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [SM-G990B, SM-G990B2]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang golang libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev \
            linux-modules-extra-$(uname -r) build-essential lld ninja-build protobuf-compiler zipalign gcc-aarch64-linux-gnu libc6-dev libarchive-tools
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch Neutron Clang and Patch glibc
        run: |
          export Kernel_DIR="$(pwd)"
          mkdir -p "$HOME/toolchains/neutron-clang"; cd "$HOME/toolchains/neutron-clang"; curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"; chmod +x antman; ./antman -S
          ./antman --patch=glibc
          cd $Kernel_DIR

      - name: Fetch AnyKernel3
        run: |
          git clone https://github.com/glikched/AnyKernel3 -b r9q ./AnyKernel3

      - name: Build Kernel Clean
        run: |
          source ./build_script.sh ${{ matrix.target }}
          cp ./AnyKernel3/AQUA* ./

      - name: Clean Kernel Source
        run: |
          make mrproper ARCH=arm64 LLVM=1

      - name: Build Kernel With KSU
        run: |
          source ./build_script.sh ${{ matrix.target }} --ksu
          cp ./AnyKernel3/AQUA* ./

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: AQUA*
          name: AQUA-CI_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Kernel: 5.4.259-aqua
            Clang: WeebX
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
